name: umjunsik
description: Discord Bot Application.
version: 1.0.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  google_generative_ai: ^0.4.6
  nyxx: ^6.6.0
  puppeteer: ^3.17.0

dev_dependencies:
  lints: ^5.0.0
